name: Run Bot

on: [push]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install FFmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Run bot
        run: python discord_achievement_economy_bot.py